### ISSUE TITLE
twitter urls no longer show the tweet content

### ISSUE THREAD

**Issue by jrwren** [z0mbieparade/b0t#36]
looks like twitter went to JS only. There is no <title> tag that includes the tweet in the header.

It would be nice to somehow support tweets. maybe redo what their shit javascript does. I plan to tackle fixing this bug as part of hacktoberfest if you approve of my work.

**Comment by jrwren** [comment]
A quick inspection looks like web client uses a cookie and/or a bearing token for auth to api.twitter.com and there are many include options by default for the web client. Some might be nice to use, others can probably be removed.

`curl 'https://api.twitter.com/2/timeline/conversation/1310594994693009415.json?simple_quoted_tweet=true&count=1&include_ext_has_birdwatch_notes=false&ext=mediaStats%2ChighlightedLabel' -X 'GET' -H 'Accept: */*' -H 'Authorization: Bearer ***' -H 'Accept-Language: en-us' -H 'Accept-Encoding: gzip, deflate' -H 'Host: api.twitter.com' -H 'Origin: https://twitter.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15' -H 'Referer: https://twitter.com/MikeOkuda/status/1310594994693009415' -H 'Connection: keep-alive' -H 'Cookie: ct0=***; gt=***; guest_id=v1%***; personalization_id="v1_***"' -H 'x-guest-token: ***' -H 'x-twitter-client-language: en' -H 'x-csrf-token: ***' -H 'x-twitter-active-user: yes' `

query params: `include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=20&include_ext_has_birdwatch_notes=false&ext=mediaStats%2ChighlightedLabel`

**Comment by z0mbieparade** [comment]
this issue was fixed with addition of the twitter API
